# bits_config.yaml

# Define reusable action groups first

actions:

  - &valid_data
    check::has_role:
      mars: "valid_forecast"

  - &era5_data
    check::match:
      class: "ea"
      stream: "oper"
  - &era5_license
    check::has_license:
      copernicus: "era5"

  - &mars_od
    route::mars_destination:
      host: "mars.ecmwf.int"
      port: 8080

  - &metkit_expansion
    via::metkit_expansion: {}

routes:

  operational_forecast:
    - *metkit_expansion
    - *valid_data
    - *mars_od

  era5_reanalysis:
    - *metkit_expansion
    - switch:
        era5_priveleged:
          - *era5_data
          - *era5_license
          - route::dss_destination: {}
        era5_public:
          - *era5_data
          - route::dss_destination: {}

  extremes_dt:
    - *valid_data
    - *metkit_expansion
    - route::dss_destination: {}

  extremes_fc:
    - *valid_data
    - *metkit_expansion
    - route::dss_destination: {}
