apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: bits-broker
build:
  local:
    useBuildkit: true
    concurrency: 1

  tagPolicy:
    envTemplate:
      template: '{{default .CARGO_VERSION "dev"}}'

  artifacts:
    - image: "bits-ecmwf"
      context: .
      docker:
        dockerfile: bits-ecmwf/Dockerfile
        target: release

    - image: "bits-ecmwf-debug"
      context: .
      docker:
        dockerfile: bits-ecmwf/Dockerfile
        target: debug
