[package]
name = "bits-ecmwf"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bits-ecmwf"
path = "src/bin/main.rs"

[dependencies]
bits = { path = "../bits" }
authotron-types = { git = "https://github.com/ecmwf/auth-o-tron.git", branch = "main", package = "authotron-types" }
async-trait = "0.1.88"
bytes = "1.10.1"
chrono = { version = "0.4", features = ["clock"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9"
futures = "0.3"
inventory = "0.3"
roxmltree = "0.20"
tokio = { version = "1.46.1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
