# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "bits-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bits-server"
path = "src/main.rs"

[dependencies]
bits = { path = "../bits", features = ["metrics-prometheus"] }
tokio = { version = "1.46.1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
